
// <auto-generated> CUFramework Auto Generate, Do not modify manually.
// Audio enums for user customization.
// Generated on 2026-05-11 18:22:06
#if CU_CUSTOM_ENABLED
namespace CUFramework.Custom
{
    public enum MusicKey { Background }
    public enum UIKey { Click }
    public enum VoiceKey { None }
    public enum EffectKey { FootStep }
}
#endif