
// <auto-generated> CUFramework Auto Generate, Do not modify manually.
// GameObjectPool enums for user customization.
// Generated on 2026-05-11 18:22:06
#if CU_CUSTOM_ENABLED
namespace CUFramework.Custom
{
    public enum PoolKey { None }
}
#endif